// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: protobuff/coms.proto

package reversepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Std struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In  string `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	Out string `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	Err string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Std) Reset() {
	*x = Std{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_coms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Std) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Std) ProtoMessage() {}

func (x *Std) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_coms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Std.ProtoReflect.Descriptor instead.
func (*Std) Descriptor() ([]byte, []int) {
	return file_protobuff_coms_proto_rawDescGZIP(), []int{0}
}

func (x *Std) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Std) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *Std) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ReverseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Std *Std `protobuf:"bytes,1,opt,name=std,proto3" json:"std,omitempty"`
}

func (x *ReverseRequest) Reset() {
	*x = ReverseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_coms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseRequest) ProtoMessage() {}

func (x *ReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_coms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseRequest.ProtoReflect.Descriptor instead.
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_coms_proto_rawDescGZIP(), []int{1}
}

func (x *ReverseRequest) GetStd() *Std {
	if x != nil {
		return x.Std
	}
	return nil
}

type ReverseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Std *Std `protobuf:"bytes,1,opt,name=std,proto3" json:"std,omitempty"`
}

func (x *ReverseResponse) Reset() {
	*x = ReverseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_coms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResponse) ProtoMessage() {}

func (x *ReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_coms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResponse.ProtoReflect.Descriptor instead.
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_coms_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseResponse) GetStd() *Std {
	if x != nil {
		return x.Std
	}
	return nil
}

var File_protobuff_coms_proto protoreflect.FileDescriptor

var file_protobuff_coms_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22,
	0x39, 0x0a, 0x03, 0x73, 0x74, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x30, 0x0a, 0x0e, 0x72, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03,
	0x73, 0x74, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x2e, 0x73, 0x74, 0x64, 0x52, 0x03, 0x73, 0x74, 0x64, 0x22, 0x31, 0x0a, 0x0f,
	0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x03, 0x73, 0x74, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x73, 0x74, 0x64, 0x52, 0x03, 0x73, 0x74, 0x64, 0x32,
	0x4a, 0x0a, 0x0a, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x54, 0x43, 0x50, 0x12, 0x3c, 0x0a,
	0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x72, 0x65, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuff_coms_proto_rawDescOnce sync.Once
	file_protobuff_coms_proto_rawDescData = file_protobuff_coms_proto_rawDesc
)

func file_protobuff_coms_proto_rawDescGZIP() []byte {
	file_protobuff_coms_proto_rawDescOnce.Do(func() {
		file_protobuff_coms_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuff_coms_proto_rawDescData)
	})
	return file_protobuff_coms_proto_rawDescData
}

var file_protobuff_coms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuff_coms_proto_goTypes = []interface{}{
	(*Std)(nil),             // 0: reverse.std
	(*ReverseRequest)(nil),  // 1: reverse.reverseRequest
	(*ReverseResponse)(nil), // 2: reverse.reverseResponse
}
var file_protobuff_coms_proto_depIdxs = []int32{
	0, // 0: reverse.reverseRequest.std:type_name -> reverse.std
	0, // 1: reverse.reverseResponse.std:type_name -> reverse.std
	1, // 2: reverse.ReverseTCP.Execute:input_type -> reverse.reverseRequest
	2, // 3: reverse.ReverseTCP.Execute:output_type -> reverse.reverseResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuff_coms_proto_init() }
func file_protobuff_coms_proto_init() {
	if File_protobuff_coms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuff_coms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Std); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_coms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_coms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuff_coms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_coms_proto_goTypes,
		DependencyIndexes: file_protobuff_coms_proto_depIdxs,
		MessageInfos:      file_protobuff_coms_proto_msgTypes,
	}.Build()
	File_protobuff_coms_proto = out.File
	file_protobuff_coms_proto_rawDesc = nil
	file_protobuff_coms_proto_goTypes = nil
	file_protobuff_coms_proto_depIdxs = nil
}
