apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundkube
  labels:
    app: roundcube
spec:
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name:  roundcube
          image: roundcube/roundcubemail
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: roundcube-service
spec:
  selector:
    app: roundcube
  ports:
    - name: webservice
      protocol: TCP
      port: 80
      targetPort: 8181
