name: blackhat docker

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./BlackHatGo/vpn/Dockerfile
          push: true
          tags: oonray/blackhat:latest

  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: mkdir -p artifacts

      - run: GOOS=windows GOARCH=amd64 go  build  -o artifacts/win64-oddproxy ./BlackHatGo/oddproxy/main.go
      - run: GOOS=windows GOARCH=386   go  build  -o artifacts/win32-oddproxy ./BlackHatGo/oddproxy/main.go
      - run: GOOS=linux   GOARCH=amd64 go  build  -o artifacts/lin64-oddproxy ./BlackHatGo/oddproxy/main.go
      - run: GOOS=linux   GOARCH=386   go  build  -o artifacts/lin32-oddproxy ./BlackHatGo/oddproxy/main.go

      - uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: 1.0
          artifacts: artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
