name: blackhat docker

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./BlackHatGo/vpn/Dockerfile
          push: true
          tags: oonray/blackhat:latest

  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: mkdir -p artifacts
      - run: sudo apt-get install -y python3 python3-dev gcc-mingw-w64-x86-64 gcc-mingw-w64-i686

      - run: GOOS=windows GOARCH=amd64 go  build  -o artifacts/win64-oddproxy.exe BlackHatGo/oddproxy/main.go
      - run: GOOS=windows GOARCH=386   go  build  -o artifacts/win32-oddproxy.exe BlackHatGo/oddproxy/main.go
      - run: GOOS=linux   GOARCH=amd64 go  build  -o artifacts/lin64-oddproxy     BlackHatGo/oddproxy/main.go
      - run: GOOS=linux   GOARCH=386   go  build  -o artifacts/lin32-oddproxy     BlackHatGo/oddproxy/main.go

      - run: GOOS=windows GOARCH=amd64 go  build  -o artifacts/win64-socks5.exe BlackHatGo/socks5/socks5.go
      - run: GOOS=windows GOARCH=386   go  build  -o artifacts/win32-socks5.exe BlackHatGo/socks5/socks5.go
      - run: GOOS=linux   GOARCH=amd64 go  build  -o artifacts/lin64-socks5     BlackHatGo/socks5/socks5.go
      - run: GOOS=linux   GOARCH=386   go  build  -o artifacts/lin32-socks5     BlackHatGo/socks5/socks5.go

      #- run: CC=x86_64-w64-mingw32-gcc  GOOS=windows GOARCH=amd64  CGO_ENABLED=1  go  build  -o artifacts/win64-python.exe BlackHatGo/python/main.go
      - run: CC=i686-w64-mingw32-gcc    GOOS=windows GOARCH=386    CGO_ENABLED=1  go  build  -o artifacts/win32-python.exe BlackHatGo/python/main.go
      - run: CC=x86_64-w64-mingw32-gcc  GOOS=linux   GOARCH=amd64  CGO_ENABLED=1  go  build  -o artifacts/lin64-python     BlackHatGo/python/main.go
      - run: CC=i686-w64-mingw32-gcc    GOOS=linux   GOARCH=386    CGO_ENABLED=1  go  build  -o artifacts/lin32-python     BlackHatGo/python/main.go

      - run: GOOS=windows GOARCH=amd64 go  build  -o artifacts/win64-tcpforwarder.exe BlackHatGo/tcpforwarder/main.go
      - run: GOOS=windows GOARCH=386   go  build  -o artifacts/win32-tcpforwarder.exe BlackHatGo/tcpforwarder/main.go
      - run: GOOS=linux   GOARCH=amd64 go  build  -o artifacts/lin64-tcpforwarder     BlackHatGo/tcpforwarder/main.go
      - run: GOOS=linux   GOARCH=386   go  build  -o artifacts/lin32-tcpforwarder     BlackHatGo/tcpforwarder/main.go

      - uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: 1.0
          artifacts: artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
