name: blackhat docker

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./BlackHatGo/vpn/Dockerfile
          push: true
          tags: oonray/blackhat:latest

  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: make artifacts repo
        run: mkdir -p /opt/artifacts

      # oddproxy
      # win64
      - name: compile
        uses:
          - actions/checkout@v2
          - actions/setup-go@v2
        run: GOOS=windows GOARCH=amd64 go -o /opt/artifacts/win64-oddproxy build BlacHatGo/oddproxy/
        run: GOOS=windows GOARCH=386   go -o /opt/artifacts/win32-oddproxy build BlacHatGo/oddproxy/
        run: GOOS=linux   GOARCH=amd64 go -o /opt/artifacts/lin64-oddproxy build BlacHatGo/oddproxy/
        run: GOOS=linux   GOARCH=386   go -o /opt/artifacts/lin32-oddproxy build BlacHatGo/oddproxy/


      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          name: all
          path: /opt/artifacts/*
